# Generated by Django 4.2.20 on 2025-05-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_info',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='Контакт для связи'),
            preserve_default=False,
        ),
    ]
