# Generated by Django 4.2.20 on 2025-05-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ad_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('auto', 'Авто'), ('real_estate', 'Недвижимость'), ('services', 'Услуги'), ('animals', 'Животные'), ('recreation_and_entertainment', 'Отдых и развлечения')], max_length=50),
        ),
    ]
