# Generated by Django 4.2.20 on 2025-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('auto', 'Авто'), ('animals', 'Животные'), ('furniture', 'Мебель'), ('decorations', 'Украшения'), ('recreation_and_entertainment', 'Отдых и развлечения')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('null', 'Не указано'), ('new', 'Новый'), ('used', 'Б/у'), ('broken', 'Требует ремонта')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
